---
- block:
    - name: "Ensure the system is joined in domain or workgroup."
      debug:
        msg: |
           {% if "{{ ansible_windows_domain_member }}" == 'false' %}
                 This machine joined in - "{{ ansible_windows_domain }}"
           {% else %}
                 This machine joined in - "{{ ansible_windows_domain }}"
           {% endif %}

    - name: "Validating the User Status."
      win_user:
        name: "{{ Win_Local_User }}"
        state: query
      register: user_status
      when: ansible_windows_domain_member == "false"

    - name: User Status - Domain
      win_domain_user:
        name: remotely
        state: query
      register: user_status
      when: ansible_windows_domain_member != "false"

    - name: "Failure User Status."
      debug:
        msg: "User is not there"
      when: user_status.state != "present"

    - name: "Success User Status."
      debug:
        msg: "User is there"
      when: user_status.state == "present"

  rescue:

    - name: "Creating the Domain User."
      win_domain_user:
        name: "{{ Win_Local_User }}"
        state: present
      when: 
        - user_status.state != "present"
        - ansible_windows_domain_member != "false"
    
    - name: "Creating the Local User."
      win_user:
        name: "{{ Win_Local_User }}"
        state: present
      when:
        - user_status.state != "present"
        - ansible_windows_domain_member == "false"

    - name: Ensure the system is joined in domain or workgroup.
      debug:
        msg: |
           {% if "{{  user_status.state}}" == 'present' %}
                 User Successfully Created...!
           {% else %}
                 Couldn't Create the User...!
           {% endif %}


