---
- block:

    - name: "Retrieve the installation status of active directory module"
      win_shell: "{{ Win_Shell_Module_Command }} -ListAvailable|Where Name -eq {{ Win_Shell_Module_Name }}"
      register: module_validate

    - name: "Validate the installation status of active directory module"
      fail:
        msg: "{{ Win_Shell_Module_Name }} module is currenlty not installed. Proceeding with the installation..."
      when: "module_validate.stdout_lines | length < 1"

    - name: "Error Handler success event for AD module validation."
      debug:
         msg: "{{ Win_Shell_Module_Name }} module already exists..!"
       
  rescue:

    - name: "Install Active Directory Module"
      win_feature:
        name: "{{ Win_Package_Name }}"
        state: "{{ Win_State }}"
      when: "module_validate.stdout_lines | length < 1"

    - name: "Error Handler success event for AD module installation"
      assert:
        that: 
          - module_validate.stdout_lines | length < 1
        fail_msg: "Failed to install the {{ Win_Shell_Module_Name }} module"
        success_msg: "Successfully installed the {{ Win_Shell_Module_Name }} module..!"

