---
- block:

    - name: "Ensure the module is exist or not."
      win_shell: "{{ Win_Shell_Module_Command }}" -ListAvailable|Where Name -eq "{{ Win_Shell_Module_Name }}"
      register: module_validate

    - name: "Validating the module is exist or not."
      fail:
        msg: "{{ Win_Shell_Module_Name }} feature is not enabled/available in the machine."
      when: "module_validate.stdout_lines | length < 1"

    - name: "Debug Message For existed."
      debug:
         msg: "{{ Win_Shell_Module_Name }} feature already enabled..!"
       
    rescue:

     - name: "Installation on Active Directory"
       win_feature:
         name: "{{ Win_Package_Name }}"
         state: "{{ Win_State }}"
       when: "module_validate.stdout_lines | length < 1"

     - name: "Success Message"
       assert:
         that: 
           - module_validate.stdout_lines | length < 1
         fail_msg: "Not properly Installted the Required {{ Win_Shell_Module_Name }} Package..!"
         success_msg: " Installed the Required {{ Win_Shell_Module_Name }} package..!"

