---
- block:
    - name: "Validate if the computer is part of domain or workgroup."
      debug:
        msg: "This machine is part of - {{ ansible_windows_domain }}"

    - name: "Validate the user account existence"
      win_user:
        name: "{{ Win_Local_User }}"
        state: query
      register: user_status

    - name: "Error Handler for failure event - queried user do not exist"
      debug:
        msg: "User do not exist. Creating the user account.."
      when: user_status.state != "present"
  
    - name: "Error Handler for success event - queried user exist"
      debug:
        msg: "User already exists..!"
      when: user_status.state == "present"
    
    rescue:
      
      - name: "Create the user account"
        win_user:
          name: "{{ Win_Local_User }}"
          state: present
        when: user_status.state != "present"

      - name: "Error Handler for success event - User creation is successful"
        debug:
          msg: "{{ Win_Local_User }} is successfully created..!"
