---
- name: "Check if a service is installed."
  win_service:
    name: IISAdmin
  register: service_info

- name: "Error Handler Success/Failure Event for IIS-Service."
  debug:
    msg: |
      {% if "{{ service_info.exists }}" == 'false' %}
      IIS-Service is not yet installed...
      {% else %}
      IIS-Service is already installed on this system..
      {% endif %}

- name: "Install IIS Web-Server with sub features and management tools."
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: True
    include_management_tools: True
  register: win_feature
  when: service_info.exists != "false"

- name: "Error Handler Success/Failure Event for IIS-Service."
  debug:
    msg: |
      {% if "{{ win_feature.state }}" == 'running' %}
      IIS-Service is succeessfully installed and it's running..
      {% else %}
      IIS-Service is not properly installed..
      {% endif %}


