---
- name: "Check if IIS service is configured."
  win_service:
    name: IISAdmin
  register: service_info

- name: "Error Handler Success/Failure Event for IIS-Service."
  debug:
    msg: |
      {% if "{{ service_info.exists }}" == "false" %}
      IIS-Service is not installed. Enabling the feature...
      {% else %}
      IIS-Service already exists..!
      {% endif %}

- name: "Install IIS feature and management tools."
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: True
    include_management_tools: True
  register: win_web_server

- name: "Error Handler Success/Failure Event for IIS installation."
  debug:
    msg: |
      {% if "{{ win_web_server.success }}" != "true" %}
      IIS is succeessfully installed..!
      {% else %}
      IIS installation failed.
      {% endif %}


