---
- name: "IIS site Configuration"
  win_iis_website:
    name: "{{ website_name }}"
    state: started
    port: "{{ website_port }}"
    ip: '*'
    hostname: '*'
    application_pool: "{{ app_pool_name }}"
    physical_path: "{{ website_physicalpath }}"
    parameters: logfile.directory:"{{ website_logpath }}"
  register: website

- name: "Create an application pool"
  win_iis_webapppool:
    name: "{{ app_pool_name }}"
    state: started

- name: "Create webapplication on IIS."
  win_iis_webapplication:
    name: "{{ app_name }}"
    application_pool: "{{ app_pool_name }}"
    site: "{{ website_name }}"
    state: present
    physical_path: "{{ app_physical_path }}"

- name: "Create a virtual directory on an application if it does not exist"
  win_iis_virtualdirectory:
    name: "{{ site_virtualdirectory_name }}"
    site: "{{ website_name }}"
    application: "{{ application_name }}"
    state: present
    physical_path: "{{ virtual_physical_path }}"

# - name: "Website https biding to specific port"
#   win_iis_webbinding:
#     name: "{{ website_name }}"
#     protocol: https
#     port: 443
#     certificate_hash: "{{ certificate }}"
#     ssl_flags: 1
#     state: present
#     certificate_store_name: no

# - name: "Import certificate be used by IIS"
#   win_certificate_store:
#     path: "{{ certificate_path }}"
#     file_type: "{{ certificate_file_type }}"
#     password: "{{ certificate_password }}"
#     store_location: LocalMachine
#     store_name: "{{ certificate_store_name }}"
#     key_storage: machine
#     state: present
